/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as OutlookRouteImport } from './routes/outlook'
import { Route as MockSectorsTickerRouteImport } from './routes/mock-sectors.$ticker'
import { Route as ReportTickerIndexRouteImport } from './routes/report.$ticker.index'
import { Route as ReportTickerChallengeRouteImport } from './routes/report.$ticker.challenge'
import { Route as ReportTickerSentimentRouteImport } from './routes/report.$ticker.sentiment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const OutlookRoute = OutlookRouteImport.update({
  id: '/outlook',
  path: '/outlook',
  getParentRoute: () => rootRouteImport,
} as any)
const MockSectorsTickerRoute = MockSectorsTickerRouteImport.update({
  id: '/mock-sectors/$ticker',
  path: '/mock-sectors/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTickerIndexRoute = ReportTickerIndexRouteImport.update({
  id: '/report/$ticker/',
  path: '/report/$ticker/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTickerChallengeRoute = ReportTickerChallengeRouteImport.update({
  id: '/report/$ticker/challenge',
  path: '/report/$ticker/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTickerSentimentRoute = ReportTickerSentimentRouteImport.update({
  id: '/report/$ticker/sentiment',
  path: '/report/$ticker/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/outlook': typeof OutlookRoute
  '/mock-sectors/$ticker': typeof MockSectorsTickerRoute
  '/report/$ticker/challenge': typeof ReportTickerChallengeRoute
  '/report/$ticker/sentiment': typeof ReportTickerSentimentRoute
  '/report/$ticker/': typeof ReportTickerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/outlook': typeof OutlookRoute
  '/mock-sectors/$ticker': typeof MockSectorsTickerRoute
  '/report/$ticker/challenge': typeof ReportTickerChallengeRoute
  '/report/$ticker/sentiment': typeof ReportTickerSentimentRoute
  '/report/$ticker': typeof ReportTickerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/outlook': typeof OutlookRoute
  '/mock-sectors/$ticker': typeof MockSectorsTickerRoute
  '/report/$ticker/challenge': typeof ReportTickerChallengeRoute
  '/report/$ticker/sentiment': typeof ReportTickerSentimentRoute
  '/report/$ticker/': typeof ReportTickerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/outlook'
    | '/mock-sectors/$ticker'
    | '/report/$ticker/challenge'
    | '/report/$ticker/sentiment'
    | '/report/$ticker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/outlook'
    | '/mock-sectors/$ticker'
    | '/report/$ticker/challenge'
    | '/report/$ticker/sentiment'
    | '/report/$ticker'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/outlook'
    | '/mock-sectors/$ticker'
    | '/report/$ticker/challenge'
    | '/report/$ticker/sentiment'
    | '/report/$ticker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  OutlookRoute: typeof OutlookRoute
  MockSectorsTickerRoute: typeof MockSectorsTickerRoute
  ReportTickerChallengeRoute: typeof ReportTickerChallengeRoute
  ReportTickerSentimentRoute: typeof ReportTickerSentimentRoute
  ReportTickerIndexRoute: typeof ReportTickerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlook': {
      id: '/outlook'
      path: '/outlook'
      fullPath: '/outlook'
      preLoaderRoute: typeof OutlookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-sectors/$ticker': {
      id: '/mock-sectors/$ticker'
      path: '/mock-sectors/$ticker'
      fullPath: '/mock-sectors/$ticker'
      preLoaderRoute: typeof MockSectorsTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$ticker/': {
      id: '/report/$ticker/'
      path: '/report/$ticker'
      fullPath: '/report/$ticker/'
      preLoaderRoute: typeof ReportTickerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$ticker/challenge': {
      id: '/report/$ticker/challenge'
      path: '/report/$ticker/challenge'
      fullPath: '/report/$ticker/challenge'
      preLoaderRoute: typeof ReportTickerChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$ticker/sentiment': {
      id: '/report/$ticker/sentiment'
      path: '/report/$ticker/sentiment'
      fullPath: '/report/$ticker/sentiment'
      preLoaderRoute: typeof ReportTickerSentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  OutlookRoute: OutlookRoute,
  MockSectorsTickerRoute: MockSectorsTickerRoute,
  ReportTickerChallengeRoute: ReportTickerChallengeRoute,
  ReportTickerSentimentRoute: ReportTickerSentimentRoute,
  ReportTickerIndexRoute: ReportTickerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
